apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-gifs
  name: service-app-gifs
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-app-gifs