apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-gifs
  name: service-app-gifs
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: app-gifs 
